name:
  clone workflow 
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone 
    runs-on: ubuntu-latest 
    steps:
      
      - name: testing
        uses: appleboy/ssh-action@master 
        # uses: actions/checkout@v3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}} 
          script: |
            cd ../pub && git clone git@github.com:KheshavKumar/cmsc389T-web-template.git
