name:
  clone workflow 
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This action automatically configures Git, including SSH authentication.
        
      - name: testing
        uses: appleboy/ssh-action@master 
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}} 
          script: |
            git clone git@github.com:KheshavKumar/cmsc389T-web-template.git
