name: deployment workflow 
on:
  push:
    branches: [main]
jobs:
  job_one:
    name: Deploy 
    runs-on: ubuntu-latest 
    steps:
      - name: testing
        uses: appleboy/ssh-action@master 
        # uses: actions/checkout@v3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd ./pub/cmsc389T-web-template 
            git pull
